### ISSUE TITLE
List Directories

### ISSUE THREAD

**Issue by robertIanClarkson** [robertIanClarkson/Filesystem#1]

**Comment by MichaelZheng911** [comment]
I work on this one for now

**Comment by MichaelZheng911** [comment]
struct dirent *de;  // Pointer for directory entry 
  
    // opendir() returns a pointer of DIR type.  
    DIR *dr = opendir("."); 
  
    if (dr == NULL)  // opendir returns NULL if couldn't open directory 
    { 
        printf("Could not open current directory" ); 
        return 0; 
    } 
  
    // Refer http://pubs.opengroup.org/onlinepubs/7990989775/xsh/readdir.html 
    // for readdir() 
    while ((de = readdir(dr)) != NULL) 
            printf("%s\n", de->d_name); 
  
    closedir(dr);     
    return 0;

**Comment by MichaelZheng911** [comment]
So I did this but I do know know where to out it but it worked.

**Comment by robertIanClarkson** [comment]
are you sure that is reading from the file (volume) or just from your computer? Especially "DIR"

**Comment by MichaelZheng911** [comment]
#include <stdio.h> 
#include <dirent.h>

you would need to include these. 
So when I tested it out it reads from the directory but I can double check to make sure.

**Comment by MichaelZheng911** [comment]
Also I see what you mean no DIR was define in this header. 

ino_t  d_ino       file serial number
char   d_name[]    name of entry

int            closedir(DIR *);
DIR           *opendir(const char *);
struct dirent *readdir(DIR *);
int            readdir_r(DIR *, struct dirent *, struct dirent **);
void           rewinddir(DIR *);
void           seekdir(DIR *, long int);
long int       telldir(DIR *);


I hope this makes more sense

**Comment by robertIanClarkson** [comment]
I think you are over complicating
check out the readme up on master but look at it 'raw' it should make more sense

**Comment by robertIanClarkson** [comment]
Done. Ready to merge
