### ISSUE TITLE
special2 not copying images correctly

### ISSUE THREAD

**Issue by charte88** [robertIanClarkson/Filesystem#21]
I believe this is happening due to one or more possible issues:
   1. The text files have been working correctly because of an 
       EOF, null terminator or newline is not at the start of a line in 
       the blocks
   2. With the image file, only the first 8 bytes copied over. We 
       also need to make sure the EOF signature stays intact when 
       copied back to Linux.
   3. Let's look into write() function instead of fgets() for a 
       a possible solution, also be aware that a line in a block 
       could start at empty

**Comment by robertIanClarkson** [comment]
Added filesize to meta but didnt work @charte88
