### ISSUE TITLE
need to change listDirectories to list directories not files

### ISSUE THREAD

**Issue by robertIanClarkson** [robertIanClarkson/Filesystem#26]
I was rereading the assignment documentation and I think we need to list the child directories under a parent directory NOT the child files under a parent directory. But I could be wrong... let me know what you think

**Comment by charte88** [comment]
I added the ability for it to print files and directories. This is how the printout looks:
--files 
-folders

**Comment by charte88** [comment]
Its under the LD branch

**Comment by robertIanClarkson** [comment]
done. @charte88
